### ISSUE TITLE
Make birding work with GNIP's "full archive search" API

### ISSUE THREAD

**Issue by amontalenti** [Parsely/birding#6]
This requires a paid license from Twitter/GNIP, but should work similarly to the official API. Bad for demos, but good for scale.

https://blog.twitter.com/2015/full-archive-search-api

http://support.gnip.com/apis/search_full_archive_api/

http://support.gnip.com/apis/search_full_archive_api/api_reference.html#DataEndpoint

cc @rduplain (we're getting you a trial to this via Parse.ly)

**Comment by rduplain** [comment]
Note current limitation in #7.
